### ISSUE TITLE
Thanks for your great contribution：）

### ISSUE THREAD

**Issue by lucywsq** [ZonePG/zonepg.github.io#1]
2021/12/09 Update: I sincerely apologize for abusing the github issue system and we’ll find more proper ways to communicate with contributors in the future.

~Hi ZonePG
We are so appreciative of your contribution to fixing pylint rules through the “Let’s become Taichi contributors within 10 minutes” program. Please send an email to siqiwu@taichi.graphics with your offline address. We would deliver a hoodie to you. : ) Looking forward to hearing from you!~
~非常感谢您参与第0次十分钟成为 Taichi contributors 活动，并在 pylint 命令修复中的宝贵贡献！
为表感谢，近期太极周边会向你赶来～请麻烦将收件信息发送至运营同学 siqiwu@taichi.graphics
欢迎持续关注 Taichi 社区哦~

~Taichi 开源社区 敬上~

**Comment by ZonePG** [comment]
thx！:)地址: 合肥工业大学宣城校区电话: 18374654611姓名: 邹鹏---- Replied Message ***@***.***>Date12/08/2021 18:47 ***@***.***> ***@***.***>Subject[ZonePG/zonepg.github.io] Thanks for your great contribution：） (Issue #1)

Hi ZonePG

We are so appreciative of your contribution to fixing pylint rules through the “Let’s become Taichi contributors within 10 minutes” program. Please send an email to ***@***.*** with your offline address. We would deliver a hoodie to you. : ) Looking forward to hearing from you！

非常感谢您参与第0次十分钟成为 Taichi contributors 活动，并在 pylint 命令修复中的宝贵贡献！

为表感谢，近期太极周边会向你赶来～请麻烦将收件信息发送至运营同学 ***@***.***

欢迎持续关注 Taichi 社区哦～

Taichi 开源社区 敬上



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ZonePG/zonepg.github.io/issues/1",

"url": "https://github.com/ZonePG/zonepg.github.io/issues/1",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by lucywsq** [comment]
Hi @ZonePG 信息已经收到，后续可以邮件同步下，在 GitHub 上发布担心会有隐私相关的风险，对您有一些影响～打扰了

**Comment by ZonePG** [comment]
哈哈，没事~您在taichi issue 里通知，github 也会自动同步发送邮件给用户啦---- Replied Message ***@***.***>Date12/09/2021 10:21 ***@***.***> ***@***.******@***.***>SubjectRe: [ZonePG/zonepg.github.io] Thanks for your great contribution：） (Issue #1)

Hi @ZonePG 信息已经收到，后续可以邮件同步下，在 GitHub 上发布担心会有隐私相关的风险，对您有一些影响～打扰了



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ZonePG/zonepg.github.io/issues/1#issuecomment-989443391",

"url": "https://github.com/ZonePG/zonepg.github.io/issues/1#issuecomment-989443391",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
